<a href="https://colab.research.google.com/github/ragunandhant/HopeAI_workshop/blob/main/EducationRF.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd

In [ ]:
df = pd.read_csv("/content/drive/MyDrive/College_placement (1).csv")

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2966 entries, 0 to 2965
Data columns (total 8 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Age                2966 non-null   int64
 1   Gender             2966 non-null   object
 2   Stream             2966 non-null   object
 3   Internships        2966 non-null   int64
 4   CGPA               2966 non-null   int64
 5   Hostel             2966 non-null   int64
 6   HistoryOfBacklogs  2966 non-null   int64
 7   PlacedOrNot        2966 non-null   int64
dtypes: int64(6), object(2)
memory usage: 185.5+ KB

In [ ]:
df

,Age,Gender,Stream,Internships,CGPA,Hostel,HistoryOfBacklogs,PlacedOrNot
0,22,Male,Electronics And Communication,1,8,1,1,1
1,21,Female,Computer Science,0,7,1,1,1
2,22,Female,Information Technology,1,6,0,0,1
3,21,Male,Information Technology,0,8,0,1,1
4,22,Male,Mechanical,0,8,1,0,1
...,...,...,...,...,...,...,...,...
2961,23,Male,Information Technology,0,7,0,0,0
2962,23,Male,Mechanical,1,7,1,0,0
2963,22,Male,Information Technology,1,7,0,0,0
2964,22,Male,Computer Science,1,7,0,0,0
2965,23,Male,Civil,0,8,0,0,1

In [ ]:
df = pd.get_dummies(df,drop_first=True)

In [ ]:
df

,Age,Internships,CGPA,Hostel,HistoryOfBacklogs,PlacedOrNot,Gender_Male,Stream_Computer Science,Stream_Electrical,Stream_Electronics And Communication,Stream_Information Technology,Stream_Mechanical
0,22,1,8,1,1,1,1,0,0,1,0,0
1,21,0,7,1,1,1,0,1,0,0,0,0
2,22,1,6,0,0,1,0,0,0,0,1,0
3,21,0,8,0,1,1,1,0,0,0,1,0
4,22,0,8,1,0,1,1,0,0,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...
2961,23,0,7,0,0,0,1,0,0,0,1,0
2962,23,1,7,1,0,0,1,0,0,0,0,1
2963,22,1,7,0,0,0,1,0,0,0,1,0
2964,22,1,7,0,0,0,1,1,0,0,0,0
2965,23,0,8,0,0,1,1,0,0,0,0,0

In [ ]:
independent = df.drop(["PlacedOrNot"],axis=1)
dependent = df["PlacedOrNot"]

In [ ]:
from sklearn.model_selection import train_test_split
xtrain,xtest,ytrain,ytest = train_test_split(independent,dependent,test_size=0.2)

In [ ]:
from sklearn.ensemble import RandomForestClassifier

model = RandomForestClassifier()
model.fit(xtrain,ytrain)

RandomForestClassifier()

In [ ]:
ypred = model.predict(xtest)

In [ ]:
from sklearn.metrics import classification_report
clf_report = classification_report(ytest, ypred)

In [ ]:
print(clf_report)

              precision    recall  f1-score   support

           0       0.80      0.92      0.86       260
           1       0.93      0.82      0.87       334

    accuracy                           0.86       594
   macro avg       0.86      0.87      0.86       594
weighted avg       0.87      0.86      0.86       594

In [ ]:
param_grid = {
    'n_estimators':[50,100,90,30,100,500,200,1000],
    'criterion':['gini', 'entropy', 'log_loss'],
    'random_state':[0,2,3,4,5,6],
    'max_depth':[2,3,4,5,6,7],
    'min_samples_split':[2,3,4,5,6,7,8,9],
    'max_leaf_nodes':[2,3,4,5,6,7,8]
},

In [ ]:
from sklearn.model_selection import GridSearchCV

best = GridSearchCV(RandomForestClassifier(),param_grid,cv=5,refit=True,scoring = 'f1')
best.fit(xtrain,ytrain)
best.best_estimator_

In [ ]:
ypred = best.predict(xtest)
from sklearn.metrics import classification_report
clf_report = classification_report(ytest, ypred)
print(clf_report)

In [ ]:
pd.DataFrame.from_dict(best.cv_results_)